aliases:
  attacker: 10.10.40.5
  defender: 10.10.30.5
  router: 10.10.40.1
  server: 10.10.20.5
routes:
- interface_default_gateway: '{{ ansible_default_ipv4.gateway }}'
  interface_ip: '{{ ansible_default_ipv4.address  | default(ansible_all_ipv4_addresses[0])
    }}'
  interface_netmask: '{{ ansible_default_ipv4.netmask  | default(''24'') }}'
